/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class logs extends javax.swing.JFrame {

    /**
     * Creates new form logs
     */
    public logs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt1 = new javax.swing.JTextField();
        btnPlussViens = new javax.swing.JButton();
        btnMinussViens = new javax.swing.JButton();
        btnResetToZero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt1.setEditable(false);
        txt1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt1.setText("0");

        btnPlussViens.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnPlussViens.setText("+1");
        btnPlussViens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlussViensActionPerformed(evt);
            }
        });

        btnMinussViens.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnMinussViens.setText("-1");
        btnMinussViens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinussViensActionPerformed(evt);
            }
        });

        btnResetToZero.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnResetToZero.setText("reset");
        btnResetToZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetToZeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlussViens)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMinussViens)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResetToZero)
                .addGap(0, 122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlussViens)
                    .addComponent(btnMinussViens, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetToZero, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 263, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlussViensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlussViensActionPerformed
        // TODO add your handling code here:
//        String strSk = txt1.getText();
//        int intSkaitlis = Integer.valueOf(strSk);
//        intSkaitlis++;
//        strSk = String.valueOf(intSkaitlis);
//        txt1.setText(strSk);
//        System.out.println(intSkaitlis);
        
        txt1.setText(String.valueOf(Integer.valueOf(txt1.getText())+1));
        
    }//GEN-LAST:event_btnPlussViensActionPerformed

    private void btnResetToZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetToZeroActionPerformed
        // TODO add your handling code here:
        txt1.setText(String.valueOf(Integer.valueOf(0)));
    }//GEN-LAST:event_btnResetToZeroActionPerformed

    private void btnMinussViensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinussViensActionPerformed
        // TODO add your handling code here:
        txt1.setText(String.valueOf(Integer.valueOf(txt1.getText())-1));
    }//GEN-LAST:event_btnMinussViensActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMinussViens;
    private javax.swing.JButton btnPlussViens;
    private javax.swing.JButton btnResetToZero;
    private javax.swing.JTextField txt1;
    // End of variables declaration//GEN-END:variables
}
